Update brave

diff --git a/.github/workflows/brave.yml b/.github/workflows/brave.yml
--- a/.github/workflows/brave.yml
+++ b/.github/workflows/brave.yml
@@ -10,6 +10,7 @@ jobs:
       - name: Download DMG file
         run: |
           curl -L -o Brave-Browser.dmg https://laptop-updates.brave.com/latest/osx/Brave-Browser.dmg
+          ls -l Brave-Browser.dmg
 
       - name: Create Mount Directory
         run: |
@@ -23,9 +24,9 @@ jobs:
         run: |
           ls -lR ${{ github.workspace }}/mount
 
-      - name: List All Keys in Info.plist
+      - name: Convert Info.plist to XML
         run: |
-          defaults read ${{ github.workspace }}/mount/Brave-Browser.app/Contents/Info.plist
+          plutil -convert xml1 -o - ${{ github.workspace }}/mount/Brave-Browser.app/Contents/Info.plist || echo "Info.plist not found"
 
       - name: Unmount DMG file
         run: |
